---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - github.com/fluxcd/flux2/manifests/install
  - https://github.com/fluxcd/flux2/releases/download/v0.11.0/install.yaml
