---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: sample-flux
spec:
  interval: 1m
  url: https://github.com/LittleChimera/sample-flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: self
spec:
  interval: 5m
  path: "./kustomize/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: sample-flux
