---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: stack-all
spec:
  interval: 1m
  path: "./kustomize/stack/all"
  prune: true
  sourceRef:
    kind: GitRepository
    name: sample-flux
